version: "3"
services:  
  ladstudio:
   build:
      context: ./ui
      dockerfile: Dockerfile.dev
   ports:
    -  3001:3000
   container_name: ladstudio
   restart: always
   networks:
    -  ladnet
   depends_on:
      - ladserver
   volumes:
    -  ./ui/src:/usr/app/src
    -  ./ui/public:/usr/app/public
   
   stdin_open: true
   tty: true

  ladserver:
   build:
      context: ./api
      dockerfile: Dockerfile.dev
   ports:
     - 3080:3080
   container_name: ladserver
   restart: always
   networks:
     - ladnet
   depends_on:
      - ladb
   volumes:
    - ./api/src:/usr/app/src
 
  ladb:
    container_name: ladb
    build:
      context: ladb/
    env_file:
      - .env
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./ladb/initdb.sql:/docker-entrypoint-initdb.d/init.sql
      - ./ladb/data:/data
      - ladb_db:/var/lib/mysql  
    restart: always
    networks:
      - ladnet  
  
  grafalab:
    container_name: grafalab 
    image: grafana/grafana:8.3.10-ubuntu
    env_file:
      - .env
    ports:
      - 3000:3000
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_plugins:/var/lib/grafana/plugins
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    networks:
      - ladnet


networks:
  ladnet:
    driver: bridge

volumes:
  ladb_db:
  grafana_data:
  grafana_plugins: